import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useEditor } from '../../state/EditorContext.jsx'
import './accept-invitation.css'

export default function AcceptInvitation() { const { inviteId } = useParams(); const navigate = useNavigate(); const { invitations, acceptInvitation, declineInvitation } = useEditor(); const [error, setError] = useState(''); const invitation = invitations.find((item) => item.id === inviteId); const invitationStatus = invitation?.status || 'unavailable'; const canAccept = invitationStatus === 'pending'
  if (!invitation) return <div className="editor-invite-page"><div className="editor-invite-card"><h1>Invitation unavailable</h1><p>This invitation was cancelled, accepted, or belongs to another workspace.</p><button onClick={() => navigate('/login')}>Go to sign in</button></div></div>
  return <div className="editor-invite-page"><div className="editor-invite-card"><span className="editor-invite-mark">✦</span><span className="editor-eyebrow">ASTRO CONNECT</span><h1>{canAccept ? 'You’re invited to help' : 'Invitation unavailable'}</h1><p>{canAccept ? <><strong>{invitation.name}</strong>, join the <strong>{invitation.role}</strong> workspace for this astrologer.</> : `This invitation is ${invitationStatus}. It cannot be accepted.`}</p>{canAccept && <><div className="editor-invite-permissions"><small>ASSIGNED ACCESS</small><span>{invitation.permissions.length ? invitation.permissions.join(' · ') : 'No permissions assigned yet'}</span></div>{error && <p className="editor-error">{error}</p>}<button onClick={() => { try { acceptInvitation(inviteId); navigate('/editor/dashboard', { replace: true }) } catch (err) { setError(err.message) } }}>Accept invitation</button><button className="editor-secondary-button" onClick={() => { declineInvitation(inviteId); navigate('/login', { replace: true }) }}>Decline</button><small>Invitation expires {new Date(invitation.expiresAt).toLocaleDateString()}.</small></>}</div></div>
}
