import { useMemo, useState } from 'react'
import { CalendarClock, ChevronRight, Crown, Globe, History, IndianRupee, Play, Radio, Users, Video, X } from 'lucide-react'
import { useAppData, sessionAudiences } from '../../state/AppDataContext.jsx'
import { useAuth } from '../../state/AuthContext.jsx'
import Card from '../../components/ui/Card.jsx'
import StatusBadge from '../../components/StatusBadge.jsx'
import '../../pages/astrologer/live/astrolive.css'
import './editor-live-history.css'

const audienceLabel = (session) => sessionAudiences(session).map((item) => item === 'subscribers' ? `Subscribers${session.subscriberTier ? ` · ${session.subscriberTier}` : ''}` : item === 'followers' ? 'Followers only' : 'Public').join(' + ')
const AudienceIcon = ({ session }) => sessionAudiences(session).includes('subscribers') ? <Crown size={14} /> : sessionAudiences(session).includes('followers') ? <Users size={14} /> : <Radio size={14} />
const dateText = (value) => value ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'
const timeText = (value) => value ? new Date(value).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : '—'
const duration = (start, end) => { const value = new Date(end || '').getTime() - new Date(start || '').getTime(); return Number.isFinite(value) && value > 0 ? `${Math.max(1, Math.round(value / 60000))} min` : '—' }

function Details({ session, onClose }) { const joined = { public: Number(session.joinedPublic) || 0, followers: Number(session.joinedFollowers) || 0, subscribers: Number(session.joinedSubscribers) || 0 }; const total = joined.public + joined.followers + joined.subscribers; const heldOn = session.endedAt || session.scheduledEndAt; return <div className="live-modal-overlay" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="live-config-modal" role="dialog" aria-modal="true"><div className="live-config-header"><div><span className="live-eyebrow">Live history details</span><h2>{session.title}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={18} /></button></div><div className="live-config-body"><p className="live-list-card__desc">{session.description || 'Live astrology guidance session.'}</p><dl className="live-list-details live-detail-grid"><div><dt>Date</dt><dd><CalendarClock size={13} />{dateText(heldOn)}</dd></div><div><dt>Time</dt><dd>{timeText(session.startedAt || session.scheduledStartAt)} – {timeText(heldOn)}</dd></div><div><dt>Duration</dt><dd><Video size={13} />{duration(session.startedAt, session.endedAt)}</dd></div><div><dt>Category</dt><dd>{session.category || 'Vedic Astrology'}</dd></div><div><dt>Audience</dt><dd><AudienceIcon session={session} />{audienceLabel(session)}</dd></div><div><dt>Rate</dt><dd>₹{session.rate || '—'}/min</dd></div></dl><fieldset className="live-fieldset"><legend>Viewers joined</legend><div className="live-detail-joined"><div><Globe size={16} />{joined.public}<small>Public</small></div><div><Users size={16} />{joined.followers}<small>Followers</small></div><div><Crown size={16} />{joined.subscribers}<small>Subscribers</small></div><div className="is-total"><Users size={16} />{total}<small>Total viewers</small></div></div></fieldset><div className="live-detail-earnings"><span>Money earned from this live</span><strong><IndianRupee size={18} />₹{Number(session.earnings || 0).toLocaleString('en-IN')}</strong></div></div><div className="live-config-footer"><button type="button" className="btn btn-ghost" onClick={onClose}>Close</button><button type="button" className="btn btn-primary" onClick={() => window.alert('Replay will be available once recording is enabled for past sessions.')}><Play size={15} /> View Replay</button></div></div></div> }

export default function EditorLiveHistory() { const { currentUser } = useAuth(); const { astrologerLiveSessions = [] } = useAppData(); const editor = currentUser; const [selected, setSelected] = useState(null); const past = useMemo(() => astrologerLiveSessions.filter((session) => (!editor?.astrologerId || session.astrologerId === editor.astrologerId) && session.status === 'past').sort((a, b) => new Date(b.endedAt || b.scheduledEndAt) - new Date(a.endedAt || a.scheduledEndAt)), [astrologerLiveSessions, editor?.astrologerId]); return <section className="editor-page editor-live-page"><div className="editor-page-intro"><span className="editor-eyebrow">ASTROLOGER PORTAL · LIVE</span><h2>Live History</h2><p>Review past live broadcasts and held session details.</p></div><div className="editor-live-page-header"><div><h3>Past broadcasts</h3><span>{past.length} sessions</span></div><History size={22} color="#a87545" /></div>{past.length ? <div className="live-list-grid">{past.map((session) => <Card as="button" type="button" className="live-list-card live-list-card--past live-list-card--clickable" key={session.id} onClick={() => setSelected(session)}><div className="live-list-card__top"><StatusBadge label="Completed" /><span className="live-list-audience"><AudienceIcon session={session} />{audienceLabel(session)}</span></div><span className="live-list-card__title">{session.title}</span><p className="live-list-card__date"><CalendarClock size={13} />{dateText(session.endedAt || session.scheduledEndAt)}</p><div className="live-list-card__footer"><span className="live-list-card__viewers"><Users size={13} />{(Number(session.joinedPublic) || 0) + (Number(session.joinedFollowers) || 0) + (Number(session.joinedSubscribers) || 0)} viewers</span><span className="live-list-card__more">View details <ChevronRight size={14} /></span></div></Card>)}</div> : <Card className="live-list-empty"><History size={22} /><strong>No past broadcasts yet</strong><p>Finish a live session and it will appear here with its recorded details.</p></Card>}{selected && <Details session={selected} onClose={() => setSelected(null)} />}</section> }
