import { useAppData } from '../../state/AppDataContext.jsx'
import { useAuth } from '../../state/AuthContext.jsx'
import { useEditor } from '../../state/EditorContext.jsx'
import { hasEditorPermission } from '../../utils/editorAccess.js'
import './editor-appointments.css'

export default function EditorAppointments() {
  const { currentUser } = useAuth(); const { appointments = [], actions } = useAppData(); const { currentEditor, recordAudit } = useEditor(); const editor = currentEditor || currentUser
  const canView = hasEditorPermission(editor, 'Appointments', 'View'); const canReschedule = hasEditorPermission(editor, 'Appointments', 'Reschedule'); const canCancel = hasEditorPermission(editor, 'Appointments', 'Cancel')
  const list = appointments.filter((appointment) => !currentUser?.astrologerId || !appointment.astrologerId || appointment.astrologerId === currentUser.astrologerId)
  const reschedule = (appointment) => { const date = window.prompt('New appointment date', appointment.date || ''); const time = date && window.prompt('New appointment time', appointment.time || ''); if (!date || !time) return; actions.rescheduleAppointment({ originalId: appointment.id, date, dateIso: date, time }); recordAudit('Appointment Rescheduled', 'Appointments', `Rescheduled ${appointment.id}.`) }
  const cancel = (appointment) => { if (!window.confirm(`Cancel appointment ${appointment.id}?`)) return; actions.cancelAppointmentByAstrologer(appointment.id); recordAudit('Appointment Cancelled', 'Appointments', `Cancelled ${appointment.id}.`) }
  return <section className="editor-page"><div className="editor-page-intro"><span className="editor-eyebrow">APPOINTMENTS</span><h2>Appointment queue</h2><p>Review and manage appointments included in your assigned access.</p></div><div className="editor-panel editor-list">{list.slice(0, 12).map((appointment, index) => <article className="editor-work-item" key={appointment.id || index}><div className="editor-work-item-main"><strong>{appointment.title || appointment.customerName || appointment.clientName || 'Client appointment'}</strong><small>{appointment.date || appointment.scheduledAt || 'Scheduled appointment'} · {appointment.time || ''}</small></div><div className="editor-work-item-actions"><span className="editor-badge">{appointment.status || 'Scheduled'}</span>{canView && <button type="button" className="editor-action-link" onClick={() => { actions.viewAppointment?.(appointment.id); recordAudit('Appointment Viewed', 'Appointments', `Viewed ${appointment.id}.`) }}>View</button>}{canReschedule && appointment.status === 'Booked' && <button type="button" className="editor-action-button" onClick={() => reschedule(appointment)}>Reschedule</button>}{canCancel && appointment.status === 'Booked' && <button type="button" className="editor-action-danger" onClick={() => cancel(appointment)}>Cancel</button>}</div></article>)}{!list.length && <p className="editor-empty">No appointments found.</p>}</div></section>
}
