import { useMemo, useState } from 'react'
import { CalendarDays, Clock3, X } from 'lucide-react'
import { useAppData } from '../../state/AppDataContext.jsx'
import { useAuth } from '../../state/AuthContext.jsx'
import { useEditor } from '../../state/EditorContext.jsx'
import { hasEditorPermission } from '../../utils/editorAccess.js'
import { appointmentStatusBucket, formatDisplayDate, resolveAppointmentWindow, formatTimeRange, toIsoDate } from '../../utils/appointments.js'
import StatusBadge from '../../components/StatusBadge.jsx'
import HistoryCalendar from '../astrologer/appointments/HistoryCalendar.jsx'
import '../../pages/astrologer/appointments/appointmenthistory.css'
import './editor-appointments.css'

const statusLabel = (appointment) => appointment.rescheduledTo || appointment.rescheduledFrom ? 'Rescheduled' : appointmentStatusBucket(appointment.status) === 'completed' ? 'Completed' : appointmentStatusBucket(appointment.status) === 'cancelled' ? 'Cancelled' : 'Booked'

export default function EditorAppointments() {
  const { currentUser } = useAuth(); const { appointments = [], actions } = useAppData(); const { currentEditor, recordAudit } = useEditor(); const editor = currentEditor || currentUser
  const canReschedule = hasEditorPermission(editor, 'Appointments', 'Reschedule'); const canCancel = hasEditorPermission(editor, 'Appointments', 'Cancel')
  const astrologerId = currentUser?.astrologerId || currentEditor?.astrologerId
  const [rangeStart, setRangeStart] = useState(() => new Date()); const [selectedDate, setSelectedDate] = useState(() => new Date()); const [status, setStatus] = useState('all'); const [selected, setSelected] = useState(null)
  const history = useMemo(() => appointments.filter((appointment) => !astrologerId || appointment.astrologerId === astrologerId).sort((a, b) => (a.dateIso || '').localeCompare(b.dateIso || '')), [appointments, astrologerId])
  const filtered = useMemo(() => history.filter((appointment) => { if (status === 'all') return true; return status === 'rescheduled' ? Boolean(appointment.rescheduledTo || appointment.rescheduledFrom) : appointmentStatusBucket(appointment.status) === status }), [history, status])
  const dayAppointments = filtered.filter((appointment) => appointment.dateIso === toIsoDate(selectedDate))
  const view = (appointment) => { setSelected(appointment); actions.viewAppointment?.(appointment.id); recordAudit('Appointment Viewed', 'Appointments', `Viewed ${appointment.id}.`) }
  const cancel = () => { if (!selected || !window.confirm(`Cancel appointment ${selected.id}?`)) return; actions.cancelAppointmentByAstrologer(selected.id); recordAudit('Appointment Cancelled', 'Appointments', `Cancelled ${selected.id}.`); setSelected(null) }
  const reschedule = () => { if (!selected) return; const date = window.prompt('New appointment date', selected.dateIso || ''); const time = date && window.prompt('New appointment time', selected.time || ''); if (!date || !time) return; actions.rescheduleAppointment({ originalId: selected.id, date, dateIso: date, time }); recordAudit('Appointment Rescheduled', 'Appointments', `Rescheduled ${selected.id}.`); setSelected(null) }
  return <section className="editor-page editor-appointments-page astro-appointment-history"><div className="editor-page-intro"><span className="editor-eyebrow">APPOINTMENTS</span><h2>Appointment history</h2><p>Review the astrologer appointment calendar and manage only the actions assigned to you.</p></div><div className="editor-appointment-filters"><div><span className="editor-eyebrow">FILTER BY STATUS</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="booked">Booked</option><option value="rescheduled">Rescheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div className="editor-appointment-count"><strong>{filtered.length}</strong><span>appointments</span></div></div><div className="editor-appointment-layout"><div className="editor-panel editor-history-calendar"><HistoryCalendar appointments={filtered} rangeStart={rangeStart} onRangeChange={setRangeStart} selectedDate={selectedDate} onSelectDate={setSelectedDate} showMonthArrows /></div><div className="editor-panel editor-day-appointments"><div className="editor-panel-heading"><div><span className="editor-eyebrow">SELECTED DATE</span><h3>{formatDisplayDate(toIsoDate(selectedDate), true)}</h3></div><CalendarDays size={20} color="#a87545" /></div>{dayAppointments.length ? <div className="editor-appointment-cards">{dayAppointments.map((appointment) => <button type="button" className="editor-appointment-card" key={appointment.id} onClick={() => view(appointment)}><div className="editor-appointment-card-top"><div><strong>{appointment.customerName || appointment.clientName || 'Customer'}</strong><small>#{appointment.orderId || appointment.id}</small></div><StatusBadge label={statusLabel(appointment)} /></div><div className="editor-appointment-card-info"><span><Clock3 size={14} /> {formatTimeRange(resolveAppointmentWindow(appointment).startMin, resolveAppointmentWindow(appointment).endMin)}</span><span>₹{Number(appointment.amount || appointment.price || 0).toLocaleString('en-IN')}</span></div></button>)}</div> : <div className="editor-empty editor-day-empty">No appointments on this date.</div>}</div></div>
    {selected && <div className="editor-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><div className="editor-modal editor-appointment-modal"><div className="editor-modal-head"><div><span className="editor-eyebrow">APPOINTMENT DETAILS</span><h3>{selected.customerName || selected.clientName || 'Customer'}</h3></div><button type="button" className="editor-icon-button" onClick={() => setSelected(null)}><X size={18} /></button></div><div className="editor-detail-grid"><div><span>Date</span><strong>{formatDisplayDate(selected.dateIso, true)}</strong></div><div><span>Time</span><strong>{formatTimeRange(resolveAppointmentWindow(selected).startMin, resolveAppointmentWindow(selected).endMin)}</strong></div><div><span>Appointment ID</span><strong>#{selected.orderId || selected.id}</strong></div><div><span>Status</span><strong><StatusBadge label={statusLabel(selected)} /></strong></div></div><div className="editor-modal-actions">{canReschedule && selected.status === 'Booked' && <button type="button" className="btn btn-outline" onClick={reschedule}>Reschedule</button>}{canCancel && selected.status === 'Booked' && <button type="button" className="btn btn-danger" onClick={cancel}>Cancel Appointment</button>}<button type="button" className="btn btn-ghost" onClick={() => setSelected(null)}>Close</button></div></div></div>}
  </section>
}
