import { useMemo, useState } from 'react'
import { Megaphone, Search, Send, Save, X } from 'lucide-react'
import { createPortal } from 'react-dom'
import { useAppData } from '../../state/AppDataContext.jsx'
import { useAuth } from '../../state/AuthContext.jsx'
import { useEditor } from '../../state/EditorContext.jsx'
import { hasEditorPermission } from '../../utils/editorAccess.js'
import StatusBadge from '../../components/StatusBadge.jsx'
import './editor-campaigns.css'

const EMPTY = { name: '', description: '', date: '', endDate: '', priority: 'Medium', generalPrice: '799', personalPrice: '999', totalLimit: '50', discountPercent: '0' }

export default function EditorCampaigns() {
  const { campaigns = [] } = useAppData(); const { currentUser } = useAuth(); const { currentEditor, saveDraft, submitDraft, recordAudit } = useEditor(); const editor = currentEditor || currentUser
  const canCreate = hasEditorPermission(editor, 'Campaigns', 'Create'); const canEdit = hasEditorPermission(editor, 'Campaigns', 'Edit'); const canSubmit = hasEditorPermission(editor, 'Campaigns', 'Submit')
  const [query, setQuery] = useState(''); const [form, setForm] = useState(EMPTY); const [formOpen, setFormOpen] = useState(false); const [selected, setSelected] = useState(null); const [saved, setSaved] = useState(null)
  const filtered = useMemo(() => campaigns.filter((campaign) => `${campaign.name} ${campaign.id} ${campaign.status} ${(campaign.categories || []).map((item) => item.name).join(' ')}`.toLowerCase().includes(query.toLowerCase().trim())), [campaigns, query])
  const payload = { ...form, generalPrice: Number(form.generalPrice), personalPrice: Number(form.personalPrice), totalLimit: Number(form.totalLimit), discountPercent: Number(form.discountPercent), astrologerId: currentUser?.astrologerId }
  const save = () => { if (!form.name.trim()) return; const draft = saveDraft({ id: saved?.id, module: 'Campaigns', action: 'create', payload }); setSaved(draft); recordAudit('Campaign Created', 'Campaigns', `Created draft ${form.name}.`) }
  const submit = () => { const draft = saved || saveDraft({ module: 'Campaigns', action: 'create', payload }); submitDraft(draft.id); setSaved({ ...draft, status: 'pending' }); recordAudit('Campaign Submitted', 'Campaigns', `Submitted ${form.name} for approval.`) }
  return <section className="editor-page editor-campaigns-page"><div className="editor-page-intro"><span className="editor-eyebrow">CAMPAIGNS</span><h2>Campaign management</h2><p>Create and prepare campaigns with the same campaign workspace used by the astrologer.</p></div>
    <div className="editor-campaign-toolbar"><div className="editor-search-field"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search campaigns or category..." /></div>{canCreate && <button type="button" className="btn btn-primary" onClick={() => { setForm(EMPTY); setSaved(null); setFormOpen(true) }}><Megaphone size={16} /> Create Campaign</button>}</div>
    <div className="editor-campaign-heading"><h3>All Campaigns ({filtered.length})</h3><span>{canEdit ? 'Editor workspace' : 'View only'}</span></div>
    <div className="editor-campaign-grid">{filtered.map((campaign) => <button type="button" className="editor-campaign-card" key={campaign.id} onClick={() => setSelected(campaign)}><div className="editor-campaign-card-top"><strong>{campaign.name}</strong><StatusBadge label={campaign.status || 'Active'} /></div><div className="editor-campaign-meta"><span>{campaign.date || 'No start date'}{campaign.endDate ? ` – ${campaign.endDate}` : ''}</span><span>{campaign.priority || 'Medium'} priority</span><span>General ₹{campaign.generalPrice || 0} · Individual ₹{campaign.personalPrice || 0}</span><span>{campaign.purchasedGeneral || 0}/{campaign.totalLimit || 0} slots sold</span></div><b>View Full Details →</b></button>)}</div>{!filtered.length && <div className="editor-panel editor-empty">No campaigns match your search.</div>}
    {formOpen && createPortal(<div className="editor-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setFormOpen(false)}><div className="editor-modal editor-campaign-modal"><div className="editor-modal-head"><div><span className="editor-eyebrow">CAMPAIGN DRAFT</span><h3>Create Campaign</h3></div><button type="button" className="editor-icon-button" onClick={() => setFormOpen(false)}><X size={18} /></button></div><div className="editor-campaign-form"><label>Campaign name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Campaign name" /></label><label>Description<textarea rows="4" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe this campaign" /></label><div className="editor-inline-fields"><label>Start date<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>End date<input type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></label></div><div className="editor-inline-fields"><label>General price<input type="number" value={form.generalPrice} onChange={(event) => setForm({ ...form, generalPrice: event.target.value })} /></label><label>Individual price<input type="number" value={form.personalPrice} onChange={(event) => setForm({ ...form, personalPrice: event.target.value })} /></label></div><div className="editor-inline-fields"><label>Total slots<input type="number" value={form.totalLimit} onChange={(event) => setForm({ ...form, totalLimit: event.target.value })} /></label><label>Subscriber discount %<input type="number" min="0" max="100" value={form.discountPercent} onChange={(event) => setForm({ ...form, discountPercent: event.target.value })} /></label></div></div><div className="editor-modal-actions">{saved && <StatusBadge label={saved.status === 'pending' ? 'Pending Approval' : 'Draft'} />}<button type="button" className="btn btn-outline" onClick={save} disabled={!canEdit}><Save size={16} /> Save Draft</button>{canSubmit && <button type="button" className="btn btn-primary" onClick={submit}><Send size={16} /> Submit for Approval</button>}</div></div></div>, document.body)}
    {selected && createPortal(<div className="editor-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><div className="editor-modal"><div className="editor-modal-head"><div><span className="editor-eyebrow">CAMPAIGN DETAILS</span><h3>{selected.name}</h3></div><button type="button" className="editor-icon-button" onClick={() => setSelected(null)}><X size={18} /></button></div><div className="editor-detail-grid"><div><span>Status</span><strong><StatusBadge label={selected.status || 'Active'} /></strong></div><div><span>Campaign dates</span><strong>{selected.date || '—'} – {selected.endDate || '—'}</strong></div><div><span>Pricing</span><strong>₹{selected.generalPrice || 0} / ₹{selected.personalPrice || 0}</strong></div><div><span>Slots</span><strong>{selected.purchasedGeneral || 0} / {selected.totalLimit || 0} sold</strong></div></div><p className="editor-detail-copy">{selected.description || 'No campaign description available.'}</p></div></div>, document.body)}
  </section>
}
