import { Link } from 'react-router-dom'
import { CalendarDays, MessageCircle, ShieldCheck, Sparkles, CalendarRange, Megaphone, Radio, Gift, Tag, Flame } from 'lucide-react'
import { useAuth } from '../../state/AuthContext.jsx'
import { useEditor } from '../../state/EditorContext.jsx'
import { getEditorNavigation } from '../../utils/editorAccess.js'
import './editor-dashboard.css'

export default function EditorDashboard() {
  const { currentUser } = useAuth(); const { audit, currentEditor } = useEditor(); const navigation = getEditorNavigation(currentEditor || currentUser); const iconMap = { 'Calendar Availability': CalendarRange, Campaigns: Megaphone, Questions: MessageCircle, Appointments: CalendarDays, 'Live Scheduling': Radio, Content: ShieldCheck, 'Perks & Benefits': Gift, Discounts: Tag, 'Atonement Tracking': Flame }; const cards = navigation.filter((item) => !['Dashboard', 'My Activity', 'Profile', 'Notifications'].includes(item.label)).map((item) => ({ ...item, icon: iconMap[item.label] || ShieldCheck }))
  return <section className="editor-page editor-dashboard"><div className="hero-banner hero-banner-user adash-hero"><div className="adash-hero-art" aria-hidden="true"><span className="adash-hero-ring adash-hero-ring--1" /><span className="adash-hero-ring adash-hero-ring--2" /><span className="adash-hero-ring adash-hero-ring--3" /><span className="adash-hero-core"><Sparkles size={26} /></span></div><div className="hero-banner-content"><div className="page-eyebrow" style={{ background: 'rgba(255,255,255,0.2)', color: '#fff' }}>EDITOR PORTAL</div><h2>Welcome back, {currentUser?.name?.split(' ')[0] || 'Editor'} 👋</h2><p>Work inside the astrologer workspace with your assigned access.</p></div></div><div className="editor-stat-grid">{cards.map(({ label, icon: Icon, to }) => <Link className="editor-stat-card" to={to} key={label}><Icon size={22} /><strong>{label}</strong><span>Open workspace <b>→</b></span></Link>)}</div><div className="editor-panel"><div className="editor-panel-heading"><div><span className="editor-eyebrow">RECENT WORK</span><h3>Your activity</h3></div><Link to="/editor/activity">View all</Link></div>{audit.slice(0, 5).map((entry) => <div className="editor-activity-row" key={entry.id}><span>{entry.action}</span><small>{entry.details} · {new Date(entry.occurredAt).toLocaleString()}</small></div>)}{!audit.length && <p className="editor-empty">Your editor actions will appear here.</p>}</div></section>
}
