import { Check, Clock3, MessageCircle, Phone, PhoneOff } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../../state/AuthContext.jsx'
import { getInstantConsultations, subscribeToInstantConsultations, updateInstantConsultation } from '../../utils/instantConsultation.js'
import './instantcallastrologer.css'

const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`

export default function InstantCallAstrologer() {
  const { currentUser } = useAuth(); const astrologerId = currentUser?.id === 'astrologer-demo-alias' ? 'astrologer-demo' : currentUser?.id
  const [requests, setRequests] = useState([]); const [remaining, setRemaining] = useState(0); const [message, setMessage] = useState('')
  useEffect(() => { const refresh = (value = getInstantConsultations()) => setRequests(value); refresh(); return subscribeToInstantConsultations(refresh) }, [])
  const pending = useMemo(() => requests.find((request) => request.astrologerId === astrologerId && request.type === 'call' && request.status === 'ringing'), [astrologerId, requests])
  const active = useMemo(() => requests.find((request) => request.astrologerId === astrologerId && request.type === 'call' && request.status === 'accepted'), [astrologerId, requests])
  useEffect(() => { if (!active) return undefined; const tick = () => { const next = Math.max(0, Math.ceil(((new Date(active.startedAt).getTime() + active.durationMinutes * 60000) - Date.now()) / 1000)); setRemaining(next); if (next === 0) updateInstantConsultation(active.id, { status: 'ended', endedAt: new Date().toISOString() }) }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer) }, [active])
  const accept = () => pending && updateInstantConsultation(pending.id, { status: 'accepted', startedAt: new Date().toISOString() })
  const reject = () => pending && updateInstantConsultation(pending.id, { status: 'rejected', rejectedAt: new Date().toISOString() })
  const sendMessage = () => { if (!active || !message.trim()) return; updateInstantConsultation(active.id, { messages: [...(active.messages || []), { id: crypto.randomUUID(), sender: 'astrologer', text: message.trim(), sentAt: new Date().toISOString() }] }); setMessage('') }
  if (!pending && !active) return null
  return <aside className="instant-call-astrologer-panel" aria-live="polite">{pending && <section className="instant-call-astrologer-request"><div className="instant-call-astrologer-icon"><Phone size={22} /></div><span className="instant-call-astrologer-badge">INSTANT CALL</span><h2>{pending.userName} is calling</h2><p><Clock3 size={14} /> Requested {pending.durationMinutes} minutes ago</p><div className="instant-call-astrologer-actions"><button type="button" className="instant-call-astrologer-accept" onClick={accept}><Check size={17} /> Accept</button><button type="button" className="instant-call-astrologer-reject" onClick={reject}><PhoneOff size={17} /> Reject</button></div></section>}{active && <section className="instant-call-astrologer-active"><header><span className="instant-call-astrologer-live"><span /> Live call</span><strong>{formatTime(remaining)}</strong></header><div className="instant-call-astrologer-person"><div className="instant-call-astrologer-avatar">{active.userName.slice(0, 2).toUpperCase()}</div><div><h2>{active.userName}</h2><p>Voice consultation · {active.durationMinutes} min</p></div></div><div className="instant-call-astrologer-conversation">{(active.messages || []).map((entry) => <p key={entry.id} className={`instant-call-astrologer-message instant-call-astrologer-message--${entry.sender}`}>{entry.text}</p>)}<small><MessageCircle size={13} /> You can send a message while speaking</small></div><div className="instant-call-astrologer-composer"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Send a message..." onKeyDown={(event) => event.key === 'Enter' && sendMessage()} /><button type="button" onClick={sendMessage}><MessageCircle size={16} /></button></div><button type="button" className="instant-call-astrologer-end" onClick={() => updateInstantConsultation(active.id, { status: 'ended', endedAt: new Date().toISOString() })}><PhoneOff size={17} /> End Call</button></section>}{!pending && !active && <div className="instant-call-astrologer-empty"><Phone size={24} /><strong>No instant calls</strong><span>Incoming requests will appear here on every astrologer page.</span></div>}</aside>
}
