import { BadgeCheck, Bookmark, CalendarDays, CalendarPlus, Grid3X3, Heart, MessageCircle, PhoneCall, Radio, Share2, Star, UserCheck, UserPlus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import Card from '../components/ui/Card.jsx'
import PageHeader from '../components/ui/PageHeader.jsx'
import { consultationAstrologers } from '../data/consultationAstrologers.js'
import { mockAstrologerPosts } from '../data/notificationData.js'
import { useAppData } from '../state/AppDataContext.jsx'
import { useAuth } from '../state/AuthContext.jsx'
import { getRoleRoutes } from '../utils/roleRoutes.js'

function initials(name = '') { return name.split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() || 'DR' }
function formatDate(value) { return new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) }

export default function AstrologerProfile() {
  const { astrologerId } = useParams()
  const [searchParams] = useSearchParams()
  const { currentUser } = useAuth()
  const { followedAstrologerIds, subscriptions, astrologerPosts, astrologerLiveSessions, postLikes, savedPostIds, postComments, actions } = useAppData()
  const routes = getRoleRoutes(currentUser?.role)
  const astrologer = useMemo(() => consultationAstrologers.find((item) => item.id === astrologerId) || consultationAstrologers[0], [astrologerId])
  const [tab, setTab] = useState('Posts')
  const following = followedAstrologerIds.includes(astrologer.id)
  const subscribed = subscriptions.some((item) => item.userId === currentUser?.id && item.astrologerId === astrologer.id)
  const posts = astrologerPosts.some((post) => post.astrologerId === astrologer.id) ? astrologerPosts.filter((post) => post.astrologerId === astrologer.id) : mockAstrologerPosts.filter((post) => post.astrologerId === astrologer.id)
  const liveSessions = astrologerLiveSessions.filter((session) => session.astrologerId === astrologer.id)
  const sharePost = (post) => { if (navigator.share) navigator.share({ title: post.title, text: post.body }).catch(() => {}) }

  const backTo = searchParams.get('from') === 'explore' ? routes.astrologers : routes.chatAstrologers

  return <div className="astrologer-profile-compact">
    <PageHeader eyebrow="USER PORTAL" title="Astrologer Profile" subtitle="Review the astrologer before starting your consultation." showBack backTo={backTo} />
    <Card className="section astrologer-compact-header"><div className="astrologer-compact-identity"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[linear-gradient(135deg,var(--violet-500),var(--violet-700))] text-xl font-bold text-white shadow-lg">{astrologer.profileImage ? <img className="h-full w-full object-cover" src={astrologer.profileImage} alt={`${astrologer.name} profile`} /> : initials(astrologer.name)}</div><div className="astrologer-compact-identity-copy"><div className="flex items-center gap-2" style={{ fontWeight: 700, fontSize: 18, color: 'var(--ink)' }}>{astrologer.name} <BadgeCheck size={16} className="text-[color:var(--primary)]" /></div><div className="muted">{astrologer.specialization}</div><div className="astrologer-inline-about"><span>About</span>{astrologer.bio}</div><div className="astrologer-profile-highlights"><span><strong>{astrologer.experience}</strong> Experience</span><span><Star size={13} /> <strong>{astrologer.rating || `${astrologer.ratingValue} / 5`}</strong></span><span><strong>{astrologer.reviews || `${astrologer.reviewCount} reviews`}</strong></span></div></div></div><div className="astrologer-compact-actions"><button type="button" className="btn btn-primary" onClick={() => !subscribed && actions.subscribeToAstrologer(astrologer.id, astrologer.name, currentUser?.id, currentUser?.name)}><BadgeCheck size={15} /> {subscribed ? 'Subscribed' : 'Subscribe'}</button><button type="button" className="btn btn-outline" onClick={() => actions.toggleFollow(astrologer.id, astrologer.name, following)}>{following ? <UserCheck size={15} /> : <UserPlus size={15} />} {following ? 'Following' : 'Follow'}</button>{subscribed && <div className="subscription-status" role="status"><CalendarDays size={15} /><span><strong>Subscribed</strong><small>Subscription ends in 30 days</small></span></div>}</div></Card>
    <Card className="section astrologer-compact-stats"><div className="section-title">Stats</div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}><div className="stat-card" style={{ boxShadow: 'none', border: 'none', padding: 0 }}><div className="stat-icon tone-violet"><BadgeCheck size={16} /></div><div><div className="stat-value">{Number(astrologer.followers || 0).toLocaleString('en-IN')}</div><div className="stat-label">followers</div></div></div><div className="stat-card" style={{ boxShadow: 'none', border: 'none', padding: 0 }}><div className="stat-icon tone-violet"><BadgeCheck size={16} /></div><div><div className="stat-value">{astrologer.subscribers || 1}</div><div className="stat-label">subscribers</div></div></div><div className="stat-card" style={{ boxShadow: 'none', border: 'none', padding: 0 }}><div className="stat-icon tone-violet"><CalendarPlus size={16} /></div><div><div className="stat-value">3,850</div><div className="stat-label">consultations</div></div></div></div></Card>
    <section className="astrologer-consultation"><div className="astrologer-consultation__heading"><span className="profile-kicker">CONSULTATION OPTIONS</span><h2>Consultation Options</h2></div><div className="astrologer-quick-actions"><Link to={`/chat-birth-details/${astrologer.id}`} className="btn btn-primary"><MessageCircle size={16} /> Chat</Link><Link to={`${routes.callPackages}?id=${astrologer.id}`} className="btn btn-primary"><PhoneCall size={16} /> Call</Link><Link to={`${routes.appointmentDetails}?astrologerId=${astrologer.id}`} className="btn btn-primary"><CalendarPlus size={16} /> Book Appointment</Link></div></section>
    <section className="astrologer-content astrologer-footer-content"><div className="astrologer-footer-tabs" role="tablist" aria-label="Astrologer content"><button type="button" className={tab === 'Posts' ? 'is-active' : ''} onClick={() => setTab('Posts')}><Grid3X3 size={15} /> Posts</button><button type="button" className={tab === 'Live' ? 'is-active' : ''} onClick={() => setTab('Live')}><Radio size={15} /> Live</button><button type="button" className={tab === 'Saved Posts' ? 'is-active' : ''} onClick={() => setTab('Saved Posts')}><Bookmark size={15} /> Saved Posts</button></div>{tab === 'Live' ? <div className="astrologer-live-groups"><section className="astrologer-live-group"><h3>Upcoming</h3>{liveSessions.map((session) => <article className="astrologer-live-card" key={session.id}><span className="astrologer-live-badge"><Radio size={12} /> {session.status}</span><h4>{session.title}</h4><p>{session.description || formatDate(session.scheduledStartAt)}</p></article>)}</section></div> : <div className="astrologer-post-list">{posts.filter((post) => tab !== 'Saved Posts' || savedPostIds.includes(post.id)).map((post) => <article className={`astrologer-post-card astrologer-post-card--${post.tone || 'violet'}`} key={post.id}><div className="astrologer-content-card__top"><span className="astrologer-content-card__avatar">{initials(astrologer.name)}</span><span><b>{astrologer.name}</b><small>{formatDate(post.createdAt)}</small></span></div><h3>{post.title}</h3><p>{post.body}</p><div className="astrologer-post-actions"><button type="button" onClick={() => actions.togglePostLike(post.id)}><Heart size={15} fill={postLikes[post.id] ? 'currentColor' : 'none'} /> {(post.likeCount || 0) + (postLikes[post.id] ? 1 : 0)}</button><button type="button" onClick={() => sharePost(post)}><Share2 size={15} /> Share</button><button type="button"><MessageCircle size={15} /> {postComments[post.id]?.length || post.comments?.length || 0}</button><button type="button" onClick={() => actions.toggleSavedPost(post.id)}><Bookmark size={15} fill={savedPostIds.includes(post.id) ? 'currentColor' : 'none'} /> {savedPostIds.includes(post.id) ? 'Saved' : 'Save'}</button></div></article>)}{!posts.filter((post) => tab !== 'Saved Posts' || savedPostIds.includes(post.id)).length && <div className="astrologer-post-empty"><Bookmark size={22} /><h3>{tab === 'Saved Posts' ? 'No saved posts yet' : 'No posts yet'}</h3><p>New posts from this astrologer will appear here.</p></div>}</div>}</section>
  </div>
}
