import { ArrowLeft, Check, Phone, PhoneOff, Plus, Timer } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { CALL_PACKAGES, mockAstrologers } from '../data/notificationData.js'
import { useAppData } from '../state/AppDataContext.jsx'
import { useAuth } from '../state/AuthContext.jsx'
import { getRoleRoutes } from '../utils/roleRoutes.js'

const money = (value) => `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
const formatTime = (seconds) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`

export default function CallScreen() {
  const { currentUser } = useAuth(); const { userWallet, actions } = useAppData(); const routes = getRoleRoutes(currentUser?.role); const navigate = useNavigate(); const [params] = useSearchParams()
  const astrologer = mockAstrologers.find(({ id }) => id === params.get('id')) || mockAstrologers[0]; const packageId = params.get('package') || CALL_PACKAGES[0].id; const activePackage = CALL_PACKAGES.find(({ id }) => id === packageId) || CALL_PACKAGES[0]
  const [remaining, setRemaining] = useState(activePackage.duration * 60); const [completed, setCompleted] = useState(false); const [extensionOpen, setExtensionOpen] = useState(false); const [extensionId, setExtensionId] = useState(CALL_PACKAGES[0].id); const [ending, setEnding] = useState(false); const [paidExtension, setPaidExtension] = useState(false)
  const extension = useMemo(() => CALL_PACKAGES.find(({ id }) => id === extensionId) || CALL_PACKAGES[0], [extensionId]); const balance = Number(userWallet?.balance || 0); const sufficient = balance >= extension.total
  useEffect(() => { if (completed || ending || paidExtension) return undefined; const timer = window.setInterval(() => setRemaining((value) => { if (value <= 1) { window.clearInterval(timer); setCompleted(true); return 0 } return value - 1 }), 1000); return () => window.clearInterval(timer) }, [completed, ending, paidExtension])
  const endCall = () => navigate(routes.astrologers)
  const payExtension = () => { if (!sufficient) return; actions.debitUserWallet({ amount: extension.total, astrologer: astrologer.name, duration: extension.duration, service: 'Call Extension', transactionId: `astro-connect:call-extension:${currentUser?.id || 'guest'}:${astrologer.id}:${Date.now()}` }); setPaidExtension(true); setExtensionOpen(false); setCompleted(false); setRemaining(extension.duration * 60) }
  return <main className="consultation-call"><section className="consultation-call__card call-session-card"><button type="button" className="wallet-payment-page__back" onClick={() => navigate(routes.astrologers)}><ArrowLeft size={16} /> Back to Astrologers</button><div className="consultation-call__avatar">{astrologer.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><span className="consultation-call__status"><Phone size={15} /> {completed ? 'Call ended' : 'Connected'}</span><h1>{astrologer.name}</h1><p>{astrologer.specialization}</p>{!completed && <div className="call-session-timer"><Timer size={16} /> {formatTime(remaining)} remaining</div>}{!completed && !ending && <button type="button" className="btn btn-outline" onClick={() => setEnding(true)}><PhoneOff size={16} /> End Call</button>}
  {ending && <div className="call-session-confirm"><h2>End Call?</h2><p>Are you sure you want to end this call?</p><button type="button" className="btn btn-outline" onClick={() => setEnding(false)}>Continue Call</button><button type="button" className="btn btn-primary" onClick={endCall}>End Call</button></div>}
  {completed && !extensionOpen && <div className="call-completed-state"><span className="call-completed-state__icon">{astrologer.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><h2>Call Time Completed</h2><p>Your {activePackage.duration}-minute call has ended.</p><p>Want to continue your conversation?</p><button type="button" className="btn btn-primary" onClick={() => setExtensionOpen(true)}><Plus size={16} /> Extend Call</button><button type="button" className="btn btn-outline" onClick={endCall}>End Call</button></div>}
  {extensionOpen && <div className="call-extension"><h2>Continue Your Call</h2><p>Choose additional time to continue your consultation with {astrologer.name}.</p><div className="call-extension__packages">{CALL_PACKAGES.map((item) => <button type="button" key={item.id} className={extensionId === item.id ? 'is-selected' : ''} onClick={() => setExtensionId(item.id)}><b>{item.duration} Minutes</b><strong>{money(item.total)}</strong><span>₹{item.rate}/min</span>{extensionId === item.id && <em><Check size={12} /> Selected</em>}</button>)}</div><div className="call-extension__balance"><span>Wallet Balance</span><strong>{money(balance)}</strong></div>{sufficient ? <button type="button" className="btn btn-primary" onClick={payExtension}>Continue &amp; Pay {money(extension.total)}</button> : <div className="call-extension__insufficient"><b>Insufficient Wallet Balance</b><span>Available {money(balance)} · Required {money(extension.total)} · Need {money(extension.total - balance)} more</span><button type="button" className="btn btn-primary" onClick={() => navigate(routes.walletHistory)}>Add Money</button><button type="button" className="btn btn-outline" onClick={() => setExtensionOpen(false)}>Cancel</button></div>}</div>}
  {paidExtension && <p className="call-extension__success">✓ Call Extension Confirmed · Reconnected for {extension.duration} minutes</p>}</section></main>
}
