import { ArrowLeft, Mic, Phone, PhoneOff, Volume2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { mockAstrologers } from '../data/notificationData.js'
import { useAuth } from '../state/AuthContext.jsx'

const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`

export default function VoiceCallScreen() {
  const { astrologerId } = useParams(); const { currentUser } = useAuth(); const navigate = useNavigate(); const userId = currentUser?.id || 'guest'
  const astrologer = mockAstrologers.find(({ id }) => id === astrologerId) || mockAstrologers[0]
  let stored = null
  try { stored = JSON.parse(localStorage.getItem(`astroconnect-app-data-call-session-${userId}`) || 'null') } catch { stored = null }
  const [session, setSession] = useState(stored); const [remaining, setRemaining] = useState(() => stored ? Math.max(0, Math.ceil((stored.endTime - Date.now()) / 1000)) : 0); const [ended, setEnded] = useState(stored?.status === 'completed'); const [muted, setMuted] = useState(false); const [speaker, setSpeaker] = useState(false)
  useEffect(() => { if (!session || session.status !== 'active' || ended) return; const timer = window.setInterval(() => { const next = Math.max(0, Math.ceil((session.endTime - Date.now()) / 1000)); setRemaining(next); if (next === 0) { const complete = { ...session, status: 'completed', completedAt: Date.now() }; setSession(complete); setEnded(true); localStorage.setItem(`astroconnect-app-data-call-session-${userId}`, JSON.stringify(complete)); navigate(session.returnPath || '/user/call-astrologers') } }, 1000); return () => window.clearInterval(timer) }, [ended, navigate, session])
  const endCall = () => { if (!session) return; const complete = { ...session, status: 'completed', completedAt: Date.now() }; setSession(complete); setEnded(true); localStorage.setItem(`astroconnect-app-data-call-session-${userId}`, JSON.stringify(complete)); navigate(session.returnPath || '/user/call-astrologers') }
  if (!session || session.astrologerId !== astrologer.id) return <main className="consultation-call"><section className="consultation-call__card call-session-card"><h1>Call Unavailable</h1><button type="button" className="btn btn-primary" onClick={() => navigate('/user/call-astrologers')}>Back to Astrologers</button></section></main>
  return <main className="consultation-call"><section className="consultation-call__card call-session-card"><button type="button" className="wallet-payment-page__back" onClick={() => navigate('/user/call-astrologers')}><ArrowLeft size={16} /> Back</button><div className="consultation-call__avatar">{astrologer.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><span className="consultation-call__status"><Phone size={15} /> {ended ? 'Call Ended' : 'Connected'}</span><h1>{astrologer.name}</h1><p>{astrologer.specialization}</p>{!ended ? <><p>● Online</p><div className="call-session-timer">Call Duration: {formatTime(remaining)}</div><p>Call package: {session.selectedDuration} Minutes · ₹{session.totalAmount}</p><div className="voice-call-controls"><button type="button" className={muted ? 'is-active' : ''} onClick={() => setMuted((value) => !value)}><Mic size={18} /> {muted ? 'Unmute' : 'Mute'}</button><button type="button" className={speaker ? 'is-active' : ''} onClick={() => setSpeaker((value) => !value)}><Volume2 size={18} /> Speaker</button><button type="button" className="voice-call-end" onClick={endCall}><PhoneOff size={18} /> End Call</button></div></> : <div className="call-completed-state"><h2>Call Ended</h2><p>Astrologer: {astrologer.name}</p><p>Duration: {session.selectedDuration} Minutes</p><p>Amount Paid: ₹{session.totalAmount}</p><button type="button" className="btn btn-primary" onClick={() => navigate('/user/call-astrologers')}>Back to Astrologers</button></div>}</section></main>
}
