import { Check, Clock3, MessageCircle, Send, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { consultationAstrologers } from '../../data/consultationAstrologers.js'
import { useAuth } from '../../state/AuthContext.jsx'
import { calculateInstantAmount, getInstantRate } from '../../utils/consultationPricing.js'
import { createInstantConsultation, getInstantConsultations, subscribeToInstantConsultations, updateInstantConsultation } from '../../utils/instantConsultation.js'
import './instantchatuser.css'

const durations = [5, 10, 15, 30]
const formatTime = (seconds) => `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`

export default function InstantChatUser() {
  const { astrologerId } = useParams(); const { currentUser } = useAuth(); const navigate = useNavigate()
  const astrologer = useMemo(() => consultationAstrologers.find((entry) => entry.id === astrologerId) || consultationAstrologers[0], [astrologerId])
  const [duration, setDuration] = useState(10); const rate = getInstantRate(astrologer.id, 'chat'); const [request, setRequest] = useState(null); const [draft, setDraft] = useState(''); const [remaining, setRemaining] = useState(0)
  useEffect(() => { const refresh = (requests = getInstantConsultations()) => setRequest(requests.find((entry) => entry.userId === currentUser?.id && entry.astrologerId === astrologer.id && entry.type === 'chat' && entry.status !== 'ended') || null); refresh(); return subscribeToInstantConsultations(refresh) }, [astrologer.id, currentUser?.id])
  useEffect(() => { if (request?.status !== 'accepted') return undefined; const tick = () => { const next = Math.max(0, Math.ceil(((new Date(request.startedAt).getTime() + request.durationMinutes * 60000) - Date.now()) / 1000)); setRemaining(next); if (next === 0) updateInstantConsultation(request.id, { status: 'ended', endedAt: new Date().toISOString() }) }; tick(); const timer = window.setInterval(tick, 1000); return () => window.clearInterval(timer) }, [request])
  const startChat = () => setRequest(createInstantConsultation({ type: 'chat', userId: currentUser?.id || 'guest', userName: currentUser?.name, astrologerId: astrologer.id, astrologerName: astrologer.name, durationMinutes: duration, pricePerMinute: rate, userPhone: currentUser?.phone, language: currentUser?.languages?.[0], topic: currentUser?.astrologerPreferences?.topics?.[0] }))
  const send = (event) => { event.preventDefault(); const text = draft.trim(); if (!text || request?.status !== 'accepted') return; updateInstantConsultation(request.id, { messages: [...(request.messages || []), { id: crypto.randomUUID(), sender: 'user', text, sentAt: new Date().toISOString() }] }); setDraft('') }
  const end = () => request && updateInstantConsultation(request.id, { status: 'ended', endedAt: new Date().toISOString() })
  return <main className="instant-chat-user-page"><section className="instant-chat-user-card"><header><div className="instant-chat-user-avatar">{astrologer.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><h1>{astrologer.name}</h1><p>{astrologer.specialization}</p></div><MessageCircle size={23} /></header>{!request && <div className="instant-chat-user-start"><label htmlFor="instant-chat-duration">Choose chat duration</label><select id="instant-chat-duration" value={duration} onChange={(event) => setDuration(Number(event.target.value))}>{durations.map((value) => <option key={value} value={value}>{value} minutes</option>)}</select><p className="instant-chat-user-rate">₹{rate}/min · Total ₹{calculateInstantAmount(duration, rate)}</p><button type="button" onClick={startChat}><MessageCircle size={17} /> Start Instant Chat</button></div>}{request?.status === 'ringing' && <div className="instant-chat-user-waiting"><span className="instant-chat-user-pulse" /><h2>Waiting for {astrologer.name}</h2><p>Your chat request is on the way.</p><button type="button" onClick={end}><X size={16} /> Cancel Request</button></div>}{request?.status === 'rejected' && <div className="instant-chat-user-waiting"><X size={25} /><h2>Chat declined</h2><button type="button" onClick={() => setRequest(null)}>Try Again</button></div>}{request?.status === 'accepted' && <><div className="instant-chat-user-toolbar"><span><Clock3 size={15} /> {formatTime(remaining)} remaining</span><button type="button" onClick={end}>End chat</button></div><div className="instant-chat-user-messages">{(request.messages || []).map((message) => <div key={message.id} className={`instant-chat-user-message instant-chat-user-message--${message.sender}`}>{message.text}</div>)}</div><form className="instant-chat-user-composer" onSubmit={send}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Write a message..." /><button type="submit" disabled={!draft.trim()}><Send size={16} /></button></form></>}{request?.status === 'ended' && <div className="instant-chat-user-waiting"><Check size={25} /><h2>Chat ended</h2><button type="button" onClick={() => navigate('/user/chat-astrologers')}>Back to Astrologers</button></div>}</section></main>
}
