export const CAMPAIGN_TEMPLATES = [
  {
    id: 'marriage-relationship',
    label: 'Marriage & Relationship',
    name: 'Marriage & Relationship Guidance',
    shortDescription: 'Timings, compatibility, and remedies for a happy married life.',
    description: 'Guidance on marriage timing, horoscope compatibility, love and arranged marriage, relationship conflicts, and harmony.',
    whatUsersCanAsk: 'Ask about marriage timing, partner compatibility, relationship challenges, Manglik dosha, and remedies for marital harmony.',
    exampleQuestions: [
      'When will I get married?',
      'Are we astrologically compatible for marriage?',
      'Why do I keep facing relationship conflicts?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'career-job',
    label: 'Career & Job',
    name: 'Career & Job Guidance',
    shortDescription: 'Job moves, promotions, business timing, and career direction.',
    description: 'Career timing, job changes, promotions, business decisions, and career direction based on your chart.',
    whatUsersCanAsk: 'Ask about job changes, promotions, government jobs, business moves, education-vs-career choices, and ideal career fields.',
    exampleQuestions: [
      'When should I switch jobs?',
      'Will I get a government job based on my horoscope?',
      'Is this the right time to start my own business?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'finance-wealth',
    label: 'Finance & Wealth',
    name: 'Finance & Wealth Guidance',
    shortDescription: 'Money growth, investments, and wealth-building periods.',
    description: 'Financial timing, savings, investments, debts, and periods favourable for wealth building.',
    whatUsersCanAsk: 'Ask about wealth periods, safe investments, clearing debts, income growth, and financial stability.',
    exampleQuestions: [
      'When will my financial situation improve?',
      'Should I invest in property or the stock market now?',
      'Will I be able to clear my debts this year?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'love-relationship',
    label: 'Love & Relationship',
    name: 'Love & Relationship Guidance',
    shortDescription: 'Love life, commitment, and timing of lasting bonds.',
    description: 'Love relationships, commitment, heartbreak, consent, and the timing of a lasting partnership.',
    whatUsersCanAsk: 'Ask about love compatibility, commitment timing, past relationships, and how to move forward after a breakup.',
    exampleQuestions: [
      'Will my current relationship lead to marriage?',
      'Why am I unlucky in love?',
      'Is my partner truly committed to me?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'children-family',
    label: 'Children & Family',
    name: 'Children & Family Guidance',
    shortDescription: 'Conception, children wellbeing, and family harmony.',
    description: 'Questions about children, conception timing, parenting, and family relationships.',
    whatUsersCanAsk: 'Ask about the timing of children, their studies and health, and improving family harmony.',
    exampleQuestions: [
      'When can I expect to have a child?',
      'Will my child succeed in competitive exams?',
      'How can I reduce friction in my family?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'property-home',
    label: 'Property & Home',
    name: 'Property & Home Guidance',
    shortDescription: 'Buying, selling, and building property with good timing.',
    description: 'Property purchase and sale timing, home construction, and house-related concerns.',
    whatUsersCanAsk: 'Ask about property purchases, selling at the right time, construction decisions, and Vastu remedies.',
    exampleQuestions: [
      'Is this a good time to buy a house?',
      'Should I sell my property this year?',
      'Which direction should my main door face for prosperity?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'education-studies',
    label: 'Education & Studies',
    name: 'Education & Studies Guidance',
    shortDescription: 'Studies, exams, higher education, and focus.',
    description: 'Academic performance, exam preparation, higher education decisions, and concentration.',
    whatUsersCanAsk: 'Ask about exam success, choosing a stream or university, study abroad plans, and improving concentration.',
    exampleQuestions: [
      'Which career stream suits me best after school?',
      'Will I pass the upcoming entrance exam?',
      'Should I pursue higher education abroad?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'foreign-travel',
    label: 'Foreign Travel / Settlement',
    name: 'Foreign Travel & Settlement',
    shortDescription: 'Travel timing, visas, and settling abroad.',
    description: 'Travel plans, visa approval chances, migration, and settling in a foreign country.',
    whatUsersCanAsk: 'Ask about the best time to travel, visa success, settling abroad, and returning home plans.',
    exampleQuestions: [
      'Will my visa application be approved?',
      'Will I settle permanently in another country?',
      'Is moving abroad favourable for my career?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'spiritual-remedies',
    label: 'Spiritual & Remedies',
    name: 'Spiritual & Remedies',
    shortDescription: 'Remedies, mantra, and spiritual guidance.',
    description: 'Astrological remedies, mantra practice, and spiritual questions for peace and progress.',
    whatUsersCanAsk: 'Ask about remedies for doshas, mantra recommendations, spiritual practices, and peace of mind.',
    exampleQuestions: [
      'What remedy helps reduce Rahu dosha?',
      'Which mantra should I chant daily?',
      'How can I improve my concentration through spirituality?',
    ],
    types: ['General'],
  },
  {
    id: 'general-life',
    label: 'General Life Guidance',
    name: 'General Life Guidance',
    shortDescription: 'Open-ended guidance for life, health, and daily decisions.',
    description: 'General guidance on life direction, health, happiness, and everyday decisions.',
    whatUsersCanAsk: 'Ask general questions about life direction, wellbeing, daily decisions, and personal growth.',
    exampleQuestions: [
      'What is a good direction for my life right now?',
      'Will I find happiness in the coming months?',
    ],
    types: ['General'],
  },
  {
    id: 'future-predictions',
    label: 'Future & Life Predictions',
    name: 'Future & Life Predictions',
    shortDescription: 'Yearly outlook, phase timing, and life forecasting.',
    description: 'Forecasts for upcoming periods, dasha timing, and what the future holds.',
    whatUsersCanAsk: 'Ask about the coming year, upcoming favourable phases, and what the future holds in key areas of life.',
    exampleQuestions: [
      'What does the next year hold for me?',
      'When will a good phase begin in my life?',
    ],
    types: ['General', 'Personal'],
  },
  {
    id: 'muhurat-auspicious',
    label: 'Muhurat / Auspicious Timing',
    name: 'Muhurat / Auspicious Timing',
    shortDescription: 'Auspicious dates and times for key events.',
    description: 'Choosing auspicious dates and times for ceremonies, purchases, and new beginnings.',
    whatUsersCanAsk: 'Ask for recommended dates and times for ceremonies, buying property, starting a business, or important events.',
    exampleQuestions: [
      'What is the best date for my wedding?',
      'Which day is auspicious to start my new business?',
    ],
    types: ['General', 'Personal'],
  },
]

export const CREATE_FROM_SCRATCH = {
  id: 'scratch',
  label: 'Create from Scratch',
}